name: Build

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          [
            "3.0.1",
            "3.1.4",
            "3.2.5",
            "3.4.10",
            "3.5.10",
            "3.6.15",
            "3.7.17",
            "3.8.18",
            "3.9.21",
            "3.10.16",
            "3.11.11",
            "3.12.8",
            "3.13.0",
          ]
    steps:
      - uses: actions/checkout@master
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
          pip install -r requirements.txt
          pip install .
          pip install tox
      - name: Run mypy
        if: "matrix.python-version != '2.7' && matrix.python-version != 'pypy2'"
        run: |
          pip install -U mypy
          mypy -p zxcvbn --ignore-missing-imports
      - name: Run tests
        run: |
          pytest -v
      - name: Test Compatibility
        run: |
          tox
